
def draw(nErrors, errors, word):  # Desenha o boneco
    """Draw the game's state"""
    if nErrors == 0:
        print()
        print("|----- ")
        print("|    | ")
        print("|      ")
        print("|      ", errors)
        print("|      ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 1:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|      ", errors)
        print("|      ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 2:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|    | ", errors)
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 3:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|    |\\ ", errors)
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 4:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ ", errors)
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 5:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ ", errors)
        print("|    | ")
        print("|     \\ ")
        print("_      ")
        print()
    elif nErrors == 6:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ GAME OVER!!!", errors)
        print("|    |  The word: ", word.capitalize())
        print("|   / \\ ")
        print("_      ")
        print()


def drawWin(nErrors):
    """Draw the state, when the user won. """
    if nErrors == 0:
        print()
        print("|----- ")
        print("|    | ")
        print("|      ")
        print("|      YOU WON!!!")
        print("|      ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 1:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|      YOU WON!!!")
        print("|      ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 2:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|    | YOU WON!!!")
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 3:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|    |\\ YOU WON!!!")
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 4:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ YOU WON!!!")
        print("|    | ")
        print("|      ")
        print("_      ")
        print()
    elif nErrors == 5:
        print()
        print("|----- ")
        print("|    | ")
        print("|    O ")
        print("|   /|\\ YOU WON!!!")
        print("|    | ")
        print("|     \\ ")
        print("_      ")
        print()
